---
# file: roles/postgresql/tasks/main.yml

#
# PostgreSQL relational database management system (RDBMS)
#

- name: PostgreSQL server and adapter packages
  with_items:
  - postgresql-server
  - python-psycopg2
  yum: name="{{ item }}" 

- name: Find the PostgreSQL data directory
  shell: "cat /etc/passwd | grep '^postgres:' | cut -d: -f6"
  register: postgres_home
  failed_when: postgres_home.stdout.strip() == ""
  changed_when: False

- set_fact:
    postgresql_pgdata: "{{ postgres_home.stdout.strip() }}/data"

- name: Check the PostgreSQL data directory structure
  command: postgresql-check-db-dir "{{ postgresql_pgdata | mandatory }}"
  register: pgdata_status
  changed_when: pgdata_status.rc != 0
  failed_when: False

- name: Check if manual intervention is necessary
  when: pgdata_status|changed and 'version' in pgdata_status.stdout
  fail: msg="{{ pgdata_status.stdout }}"

- name: Initialize the database cluster
  when: pgdata_status|changed and 'initdb' in pgdata_status.stdout
  command: postgresql-setup initdb 
  environment:
    PGSETUP_INITDB_OPTIONS: >
                            --no-locale
                            -D '{{ postgresql_pgdata }}'
                            -E UNICODE
  notify:
   - Restart PostgreSQL

- name: Determine the internal IP address to listen
  when: ansible_virbr0.ipv4 is defined
  set_fact:
    postgresql_listen: "{{ ansible_virbr0.ipv4.address | mandatory }}"

- when: postgresql_listen is not defined 
  set_fact:
    postgresql_listen: "{{ ansible_eth0.ipv4.address | mandatory }}"

#
# PostgreSQL configuration
# TODO: This is development configuration. Needs plenty tuning for production.
#
- name: PostgreSQL configuration
  with_items:
  - key: listen_addresses
    val: "\\'{{ postgresql_listen | mandatory }},localhost\\'"
  - key: max_connections
    val: 40
  - key: shared_buffers
    val: 24MB
  lineinfile:
    dest="{{ postgresql_pgdata }}/postgresql.conf"
    regexp="^\s*{{ item.key|mandatory }}\s*="
    line="{{ item.key|mandatory }} = {{ item.val|mandatory }}"
    insertafter='^#+\s*{{ item.key|mandatory }}'
  notify:
  - Restart PostgreSQL

#
# TODO: Further reduce the need of manual configuration. Manage apps, not CIDRs. 
#
- name: PostgreSQL host-based authentication
  template: src=pg_hba.conf.j2
            dest={{ postgresql_pgdata }}/pg_hba.conf
            owner=postgres group=postgres mode=0600
  notify:
  - Restart PostgreSQL

- name: Enable the PostgreSQL service
  service: name=postgresql enabled=yes state=started

- name: Open the internal firewall for PostgreSQL
  sudo: yes
  command: firewall-cmd --permanent --zone=internal --add-service=postgresql
  notify:
  - Reload firewall
